/* Generated By:JavaCC: Do not edit this line. RookieParserTreeConstants.java Version 7.0.5 */
package edu.berkeley.cs186.database.cli.parser;

public interface RookieParserTreeConstants
{
  public int JJTSQLSTATEMENTLIST = 0;
  public int JJTVOID = 1;
  public int JJTEXECUTABLESTATEMENT = 2;
  public int JJTEXPLAINSTATEMENT = 3;
  public int JJTDROPTABLESTATEMENT = 4;
  public int JJTDROPINDEXSTATEMENT = 5;
  public int JJTRELEASESTATEMENT = 6;
  public int JJTSAVEPOINTSTATEMENT = 7;
  public int JJTROLLBACKSTATEMENT = 8;
  public int JJTBEGINSTATEMENT = 9;
  public int JJTCOMMITSTATEMENT = 10;
  public int JJTINSERTSTATEMENT = 11;
  public int JJTINSERTVALUES = 12;
  public int JJTUPDATESTATEMENT = 13;
  public int JJTSELECTSTATEMENT = 14;
  public int JJTCOMMONTABLEEXPRESSION = 15;
  public int JJTDELETESTATEMENT = 16;
  public int JJTCREATETABLESTATEMENT = 17;
  public int JJTCREATEINDEXSTATEMENT = 18;
  public int JJTCOLUMNDEF = 19;
  public int JJTSELECTCLAUSE = 20;
  public int JJTLIMITCLAUSE = 21;
  public int JJTFROMCLAUSE = 22;
  public int JJTORDERCLAUSE = 23;
  public int JJTJOINEDTABLE = 24;
  public int JJTSELECTCOLUMN = 25;
  public int JJTRESULTCOLUMNNAME = 26;
  public int JJTCOLUMNNAME = 27;
  public int JJTIDENTIFIER = 28;
  public int JJTALIASEDTABLENAME = 29;
  public int JJTCOLUMNVALUECOMPARISON = 30;
  public int JJTNUMERICLITERAL = 31;
  public int JJTINTEGERLITERAL = 32;
  public int JJTLITERAL = 33;
  public int JJTCOMPARISONOPERATOR = 34;
  public int JJTOROPERATOR = 35;
  public int JJTANDOPERATOR = 36;
  public int JJTNOTOPERATOR = 37;
  public int JJTMULTIPLICATIVEOPERATOR = 38;
  public int JJTADDITIVEOPERATOR = 39;
  public int JJTEXPRESSION = 40;
  public int JJTOREXPRESSION = 41;
  public int JJTANDEXPRESSION = 42;
  public int JJTNOTEXPRESSION = 43;
  public int JJTCOMPARISONEXPRESSION = 44;
  public int JJTADDITIVEEXPRESSION = 45;
  public int JJTMULTIPLICATIVEEXPRESSION = 46;
  public int JJTFUNCTIONCALLEXPRESSION = 47;
  public int JJTPRIMARYEXPRESSION = 48;

  public String[] jjtNodeName = {
    "SQLStatementList",
    "void",
    "ExecutableStatement",
    "ExplainStatement",
    "DropTableStatement",
    "DropIndexStatement",
    "ReleaseStatement",
    "SavepointStatement",
    "RollbackStatement",
    "BeginStatement",
    "CommitStatement",
    "InsertStatement",
    "InsertValues",
    "UpdateStatement",
    "SelectStatement",
    "CommonTableExpression",
    "DeleteStatement",
    "CreateTableStatement",
    "CreateIndexStatement",
    "ColumnDef",
    "SelectClause",
    "LimitClause",
    "FromClause",
    "OrderClause",
    "JoinedTable",
    "SelectColumn",
    "ResultColumnName",
    "ColumnName",
    "Identifier",
    "AliasedTableName",
    "ColumnValueComparison",
    "NumericLiteral",
    "IntegerLiteral",
    "Literal",
    "ComparisonOperator",
    "OrOperator",
    "AndOperator",
    "NotOperator",
    "MultiplicativeOperator",
    "AdditiveOperator",
    "Expression",
    "OrExpression",
    "AndExpression",
    "NotExpression",
    "ComparisonExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "FunctionCallExpression",
    "PrimaryExpression",
  };
}
/* JavaCC - OriginalChecksum=7454a2bc0c1d9ffa919482951677c36d (do not edit this line) */
